# Lore Data: Load set definitions to storage
# Called from lore/load.mcfunction
# Generated by generate_lore.py — DO NOT EDIT MANUALLY
# Format: {name:"...",dim:N,cat:"...",ctx:N,rarity:N,pieces:N,dr:N,xp:N,crate:N}

# === OVERWORLD SETS ===

# Set 1: Flowers of the Plains — Common, 6 pieces (Plains)
data modify storage evercraft:lore sets.s1 set value {name:"Flowers of the Plains",dim:0,cat:"biome",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 2: Forest Whispers — Common, 6 pieces (Forest)
data modify storage evercraft:lore sets.s2 set value {name:"Forest Whispers",dim:0,cat:"biome",ctx:1,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 3: Petal Cascade — Uncommon, 5 pieces (Flower Forest)
data modify storage evercraft:lore sets.s3 set value {name:"Petal Cascade",dim:0,cat:"biome",ctx:2,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 4: Darkwood Shadows — Uncommon, 5 pieces (Dark Forest)
data modify storage evercraft:lore sets.s4 set value {name:"Darkwood Shadows",dim:0,cat:"biome",ctx:3,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 5: Frostpine Tales — Common, 6 pieces (Taiga)
data modify storage evercraft:lore sets.s5 set value {name:"Frostpine Tales",dim:0,cat:"biome",ctx:4,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 6: Summit Stones — Common, 6 pieces (Mountain)
data modify storage evercraft:lore sets.s6 set value {name:"Summit Stones",dim:0,cat:"biome",ctx:5,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 7: Jungle Relics — Uncommon, 5 pieces (Jungle)
data modify storage evercraft:lore sets.s7 set value {name:"Jungle Relics",dim:0,cat:"biome",ctx:6,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 8: Desert Mirages — Common, 6 pieces (Desert)
data modify storage evercraft:lore sets.s8 set value {name:"Desert Mirages",dim:0,cat:"biome",ctx:7,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 9: Savanna Dusk — Common, 6 pieces (Savanna)
data modify storage evercraft:lore sets.s9 set value {name:"Savanna Dusk",dim:0,cat:"biome",ctx:8,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 10: Tidal Treasures — Common, 6 pieces (Ocean)
data modify storage evercraft:lore sets.s10 set value {name:"Tidal Treasures",dim:0,cat:"biome",ctx:9,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 11: River Stones — Common, 6 pieces (River)
data modify storage evercraft:lore sets.s11 set value {name:"River Stones",dim:0,cat:"biome",ctx:10,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 12: Murky Keepsakes — Uncommon, 5 pieces (Swamp)
data modify storage evercraft:lore sets.s12 set value {name:"Murky Keepsakes",dim:0,cat:"biome",ctx:11,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 13: Mycelium Mysteries — Rare, 5 pieces (Mushroom)
data modify storage evercraft:lore sets.s13 set value {name:"Mycelium Mysteries",dim:0,cat:"biome",ctx:12,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 14: Frozen Memories — Common, 6 pieces (Ice)
data modify storage evercraft:lore sets.s14 set value {name:"Frozen Memories",dim:0,cat:"biome",ctx:13,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 15: Terracotta Chronicles — Uncommon, 5 pieces (Badlands)
data modify storage evercraft:lore sets.s15 set value {name:"Terracotta Chronicles",dim:0,cat:"biome",ctx:14,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 16: Lush Undergrowth — Uncommon, 5 pieces (Lush Caves)
data modify storage evercraft:lore sets.s16 set value {name:"Lush Undergrowth",dim:0,cat:"biome",ctx:15,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 17: Stalactite Songs — Uncommon, 5 pieces (Dripstone Caves)
data modify storage evercraft:lore sets.s17 set value {name:"Stalactite Songs",dim:0,cat:"biome",ctx:16,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 18: Sculk Whispers — Rare, 5 pieces (Deep Dark)
data modify storage evercraft:lore sets.s18 set value {name:"Sculk Whispers",dim:0,cat:"biome",ctx:17,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 19: Windswept Relics — Common, 6 pieces (Windswept)
data modify storage evercraft:lore sets.s19 set value {name:"Windswept Relics",dim:0,cat:"biome",ctx:24,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 20: Depths Below — Common, 6 pieces (Underground)
data modify storage evercraft:lore sets.s20 set value {name:"Depths Below",dim:0,cat:"biome",ctx:25,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 21: Warden's Legacy — Rare, 5 pieces (Ancient City)
data modify storage evercraft:lore sets.s21 set value {name:"Warden's Legacy",dim:0,cat:"structure",ctx:1,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 22: City of Silence — Rare, 5 pieces (Ancient City)
data modify storage evercraft:lore sets.s22 set value {name:"City of Silence",dim:0,cat:"structure",ctx:1,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 23: Pharaoh's Hoard — Uncommon, 5 pieces (Desert Pyramid)
data modify storage evercraft:lore sets.s23 set value {name:"Pharaoh's Hoard",dim:0,cat:"structure",ctx:3,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 24: Sandswept Relics — Uncommon, 5 pieces (Desert Pyramid)
data modify storage evercraft:lore sets.s24 set value {name:"Sandswept Relics",dim:0,cat:"structure",ctx:3,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 25: Frozen Hearth — Common, 6 pieces (Igloo)
data modify storage evercraft:lore sets.s25 set value {name:"Frozen Hearth",dim:0,cat:"structure",ctx:5,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 26: Ice Laboratory — Uncommon, 5 pieces (Igloo)
data modify storage evercraft:lore sets.s26 set value {name:"Ice Laboratory",dim:0,cat:"structure",ctx:5,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 27: Temple Treasures — Uncommon, 5 pieces (Jungle Pyramid)
data modify storage evercraft:lore sets.s27 set value {name:"Temple Treasures",dim:0,cat:"structure",ctx:6,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 28: Jungle Traps — Uncommon, 5 pieces (Jungle Pyramid)
data modify storage evercraft:lore sets.s28 set value {name:"Jungle Traps",dim:0,cat:"structure",ctx:6,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 29: Evoker's Collection — Rare, 5 pieces (Mansion)
data modify storage evercraft:lore sets.s29 set value {name:"Evoker's Collection",dim:0,cat:"structure",ctx:7,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 30: Mansion Secrets — Rare, 5 pieces (Mansion)
data modify storage evercraft:lore sets.s30 set value {name:"Mansion Secrets",dim:0,cat:"structure",ctx:7,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 31: Miner's Lament — Common, 6 pieces (Mineshaft)
data modify storage evercraft:lore sets.s31 set value {name:"Miner's Lament",dim:0,cat:"structure",ctx:8,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 32: Rail Tales — Common, 6 pieces (Mineshaft)
data modify storage evercraft:lore sets.s32 set value {name:"Rail Tales",dim:0,cat:"structure",ctx:8,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 33: Guardian's Trove — Uncommon, 5 pieces (Monument)
data modify storage evercraft:lore sets.s33 set value {name:"Guardian's Trove",dim:0,cat:"structure",ctx:9,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 34: Prismarine Halls — Rare, 5 pieces (Monument)
data modify storage evercraft:lore sets.s34 set value {name:"Prismarine Halls",dim:0,cat:"structure",ctx:9,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 35: Drowned Legacy — Uncommon, 5 pieces (Ocean Ruin)
data modify storage evercraft:lore sets.s35 set value {name:"Drowned Legacy",dim:0,cat:"structure",ctx:10,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 36: Coral Archives — Common, 6 pieces (Ocean Ruin)
data modify storage evercraft:lore sets.s36 set value {name:"Coral Archives",dim:0,cat:"structure",ctx:10,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 37: Raider's Cache — Uncommon, 5 pieces (Pillager Outpost)
data modify storage evercraft:lore sets.s37 set value {name:"Raider's Cache",dim:0,cat:"structure",ctx:11,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 38: Banner Tales — Common, 6 pieces (Pillager Outpost)
data modify storage evercraft:lore sets.s38 set value {name:"Banner Tales",dim:0,cat:"structure",ctx:11,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 39: Portal Fragments — Uncommon, 5 pieces (Ruined Portal)
data modify storage evercraft:lore sets.s39 set value {name:"Portal Fragments",dim:0,cat:"structure",ctx:12,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 40: Between Worlds — Rare, 5 pieces (Ruined Portal)
data modify storage evercraft:lore sets.s40 set value {name:"Between Worlds",dim:0,cat:"structure",ctx:12,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 41: Captain's Log — Common, 6 pieces (Shipwreck)
data modify storage evercraft:lore sets.s41 set value {name:"Captain's Log",dim:0,cat:"structure",ctx:13,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 42: Barnacle Bounty — Common, 6 pieces (Shipwreck)
data modify storage evercraft:lore sets.s42 set value {name:"Barnacle Bounty",dim:0,cat:"structure",ctx:13,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 43: Ender Archives — Rare, 5 pieces (Stronghold)
data modify storage evercraft:lore sets.s43 set value {name:"Ender Archives",dim:0,cat:"structure",ctx:14,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 44: Dungeon Depths — Ornate, 6 pieces (Stronghold)
data modify storage evercraft:lore sets.s44 set value {name:"Dungeon Depths",dim:0,cat:"structure",ctx:14,rarity:4,pieces:6,dr:65,xp:15,crate:4}

# Set 45: Buried History — Uncommon, 5 pieces (Trail Ruins)
data modify storage evercraft:lore sets.s45 set value {name:"Buried History",dim:0,cat:"structure",ctx:15,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 46: Archaeologist's Notes — Uncommon, 5 pieces (Trail Ruins)
data modify storage evercraft:lore sets.s46 set value {name:"Archaeologist's Notes",dim:0,cat:"structure",ctx:15,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 47: Trial Trophies — Uncommon, 5 pieces (Trial Chambers)
data modify storage evercraft:lore sets.s47 set value {name:"Trial Trophies",dim:0,cat:"structure",ctx:16,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 48: Chamber Keys — Rare, 5 pieces (Trial Chambers)
data modify storage evercraft:lore sets.s48 set value {name:"Chamber Keys",dim:0,cat:"structure",ctx:16,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 49: Village Chronicles — Uncommon, 5 pieces (Village)
data modify storage evercraft:lore sets.s49 set value {name:"Village Chronicles",dim:0,cat:"structure",ctx:17,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 50: Hearth and Home — Common, 6 pieces (Village)
data modify storage evercraft:lore sets.s50 set value {name:"Hearth and Home",dim:0,cat:"structure",ctx:17,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 51: Mob Femurs — Common, 6 pieces
data modify storage evercraft:lore sets.s51 set value {name:"Mob Femurs",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 52: Mob Feet — Common, 6 pieces
data modify storage evercraft:lore sets.s52 set value {name:"Mob Feet",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 53: Mob Eggs — Common, 6 pieces
data modify storage evercraft:lore sets.s53 set value {name:"Mob Eggs",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 54: Hostile Weapons — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s54 set value {name:"Hostile Weapons",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 55: Flower Pressing — Common, 6 pieces
data modify storage evercraft:lore sets.s55 set value {name:"Flower Pressing",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 56: Mining Logs — Common, 6 pieces
data modify storage evercraft:lore sets.s56 set value {name:"Mining Logs",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 57: Fishing Tales — Common, 6 pieces
data modify storage evercraft:lore sets.s57 set value {name:"Fishing Tales",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 58: Cooking Notes — Common, 6 pieces
data modify storage evercraft:lore sets.s58 set value {name:"Cooking Notes",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 59: Farming Almanac — Common, 6 pieces
data modify storage evercraft:lore sets.s59 set value {name:"Farming Almanac",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 60: Weather Journals — Common, 6 pieces
data modify storage evercraft:lore sets.s60 set value {name:"Weather Journals",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 61: Star Charts — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s61 set value {name:"Star Charts",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 62: Animal Studies — Common, 6 pieces
data modify storage evercraft:lore sets.s62 set value {name:"Animal Studies",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 63: Potion Recipes — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s63 set value {name:"Potion Recipes",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 64: Enchanting Lore — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s64 set value {name:"Enchanting Lore",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 65: Redstone Theory — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s65 set value {name:"Redstone Theory",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 66: Music Scores — Common, 6 pieces
data modify storage evercraft:lore sets.s66 set value {name:"Music Scores",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 67: Dream Fragments — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s67 set value {name:"Dream Fragments",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 68: Traveler's Maps — Common, 6 pieces
data modify storage evercraft:lore sets.s68 set value {name:"Traveler's Maps",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 69: Monster Field Guide — Common, 6 pieces
data modify storage evercraft:lore sets.s69 set value {name:"Monster Field Guide",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 70: Woodland Myths — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s70 set value {name:"Woodland Myths",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 71: Ocean Depths — Common, 6 pieces
data modify storage evercraft:lore sets.s71 set value {name:"Ocean Depths",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 72: Mountain Echoes — Common, 6 pieces
data modify storage evercraft:lore sets.s72 set value {name:"Mountain Echoes",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 73: Desert Sands — Common, 6 pieces
data modify storage evercraft:lore sets.s73 set value {name:"Desert Sands",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 74: Cave Paintings — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s74 set value {name:"Cave Paintings",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 75: Ancient Scripts — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s75 set value {name:"Ancient Scripts",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 76: Ghost Stories — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s76 set value {name:"Ghost Stories",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 77: Warrior's Codex — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s77 set value {name:"Warrior's Codex",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 78: Herbalist's Guide — Common, 6 pieces
data modify storage evercraft:lore sets.s78 set value {name:"Herbalist's Guide",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 79: Blacksmith's Secrets — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s79 set value {name:"Blacksmith's Secrets",dim:0,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 80: Adventurer's Diary — Common, 6 pieces
data modify storage evercraft:lore sets.s80 set value {name:"Adventurer's Diary",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 81: Builder's Notes — Common, 6 pieces
data modify storage evercraft:lore sets.s81 set value {name:"Builder's Notes",dim:0,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# === NETHER SETS ===

# Set 82: Nether Wastes Ash — Uncommon, 5 pieces (Nether Wastes)
data modify storage evercraft:lore sets.s82 set value {name:"Nether Wastes Ash",dim:1,cat:"biome",ctx:18,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 83: Blaze Wastes — Uncommon, 5 pieces (Nether Wastes)
data modify storage evercraft:lore sets.s83 set value {name:"Blaze Wastes",dim:1,cat:"biome",ctx:18,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 84: Crimson Spore Tales — Uncommon, 5 pieces (Crimson Forest)
data modify storage evercraft:lore sets.s84 set value {name:"Crimson Spore Tales",dim:1,cat:"biome",ctx:19,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 85: Crimson Canopy — Uncommon, 5 pieces (Crimson Forest)
data modify storage evercraft:lore sets.s85 set value {name:"Crimson Canopy",dim:1,cat:"biome",ctx:19,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 86: Warped Echoes — Uncommon, 5 pieces (Warped Forest)
data modify storage evercraft:lore sets.s86 set value {name:"Warped Echoes",dim:1,cat:"biome",ctx:20,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 87: Twisted Canopy — Uncommon, 5 pieces (Warped Forest)
data modify storage evercraft:lore sets.s87 set value {name:"Twisted Canopy",dim:1,cat:"biome",ctx:20,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 88: Delta Stones — Uncommon, 5 pieces (Basalt Deltas)
data modify storage evercraft:lore sets.s88 set value {name:"Delta Stones",dim:1,cat:"biome",ctx:21,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 89: Magma Fields — Rare, 5 pieces (Basalt Deltas)
data modify storage evercraft:lore sets.s89 set value {name:"Magma Fields",dim:1,cat:"biome",ctx:21,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 90: Soul Whispers — Uncommon, 5 pieces (Soul Sand Valley)
data modify storage evercraft:lore sets.s90 set value {name:"Soul Whispers",dim:1,cat:"biome",ctx:22,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 91: Valley of Bones — Rare, 5 pieces (Soul Sand Valley)
data modify storage evercraft:lore sets.s91 set value {name:"Valley of Bones",dim:1,cat:"biome",ctx:22,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 92: Bastion's Bounty — Rare, 5 pieces (Bastion Remnant)
data modify storage evercraft:lore sets.s92 set value {name:"Bastion's Bounty",dim:1,cat:"structure",ctx:2,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 93: Piglin Hoard — Rare, 5 pieces (Bastion Remnant)
data modify storage evercraft:lore sets.s93 set value {name:"Piglin Hoard",dim:1,cat:"structure",ctx:2,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 94: Fortress Archives — Uncommon, 5 pieces (Fortress)
data modify storage evercraft:lore sets.s94 set value {name:"Fortress Archives",dim:1,cat:"structure",ctx:4,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 95: Blaze Quarters — Rare, 5 pieces (Fortress)
data modify storage evercraft:lore sets.s95 set value {name:"Blaze Quarters",dim:1,cat:"structure",ctx:4,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 96: Nether Ores — Common, 6 pieces
data modify storage evercraft:lore sets.s96 set value {name:"Nether Ores",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 97: Lava Fishing — Common, 6 pieces
data modify storage evercraft:lore sets.s97 set value {name:"Lava Fishing",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 98: Piglin Trading — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s98 set value {name:"Piglin Trading",dim:1,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 99: Wither Cult — Rare, 5 pieces
data modify storage evercraft:lore sets.s99 set value {name:"Wither Cult",dim:1,cat:"universal",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 100: Nether Flora — Common, 6 pieces
data modify storage evercraft:lore sets.s100 set value {name:"Nether Flora",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 101: Ghast Journals — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s101 set value {name:"Ghast Journals",dim:1,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 102: Nether Masonry — Common, 6 pieces
data modify storage evercraft:lore sets.s102 set value {name:"Nether Masonry",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 103: Strider Tales — Common, 6 pieces
data modify storage evercraft:lore sets.s103 set value {name:"Strider Tales",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 104: Gold Rush — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s104 set value {name:"Gold Rush",dim:1,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 105: Nether Survival — Common, 6 pieces
data modify storage evercraft:lore sets.s105 set value {name:"Nether Survival",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 106: Blaze Academy — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s106 set value {name:"Blaze Academy",dim:1,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 107: Crimson Cuisine — Common, 6 pieces
data modify storage evercraft:lore sets.s107 set value {name:"Crimson Cuisine",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 108: Dimension Rifts — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s108 set value {name:"Dimension Rifts",dim:1,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 109: Ancient Nether — Rare, 5 pieces
data modify storage evercraft:lore sets.s109 set value {name:"Ancient Nether",dim:1,cat:"universal",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 110: Skull Collection — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s110 set value {name:"Skull Collection",dim:1,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 111: Nether Soundscapes — Common, 6 pieces
data modify storage evercraft:lore sets.s111 set value {name:"Nether Soundscapes",dim:1,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# === END SETS ===

# Set 112: Void Stones — Uncommon, 5 pieces (The End)
data modify storage evercraft:lore sets.s112 set value {name:"Void Stones",dim:2,cat:"biome",ctx:23,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 113: End City Treasures — Ornate, 6 pieces (End City)
data modify storage evercraft:lore sets.s113 set value {name:"End City Treasures",dim:2,cat:"structure",ctx:18,rarity:4,pieces:6,dr:65,xp:15,crate:4}

# Set 114: Shulker Archives — Rare, 5 pieces (End City)
data modify storage evercraft:lore sets.s114 set value {name:"Shulker Archives",dim:2,cat:"structure",ctx:18,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 115: Dragon Relics — Rare, 5 pieces
data modify storage evercraft:lore sets.s115 set value {name:"Dragon Relics",dim:2,cat:"universal",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 116: Chorus Gardens — Common, 6 pieces
data modify storage evercraft:lore sets.s116 set value {name:"Chorus Gardens",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 117: Ender Pearl Studies — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s117 set value {name:"Ender Pearl Studies",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 118: Void Walker's Log — Common, 6 pieces
data modify storage evercraft:lore sets.s118 set value {name:"Void Walker's Log",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 119: Enderman Studies — Common, 6 pieces
data modify storage evercraft:lore sets.s119 set value {name:"Enderman Studies",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 120: End Island Survey — Common, 6 pieces
data modify storage evercraft:lore sets.s120 set value {name:"End Island Survey",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 121: Crystal Resonance — Rare, 5 pieces
data modify storage evercraft:lore sets.s121 set value {name:"Crystal Resonance",dim:2,cat:"universal",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 122: Shulker Biology — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s122 set value {name:"Shulker Biology",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 123: End Stone Geology — Common, 6 pieces
data modify storage evercraft:lore sets.s123 set value {name:"End Stone Geology",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 124: Elytra Legends — Rare, 5 pieces
data modify storage evercraft:lore sets.s124 set value {name:"Elytra Legends",dim:2,cat:"universal",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 125: Obsidian Pillars — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s125 set value {name:"Obsidian Pillars",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 126: End Ship Salvage — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s126 set value {name:"End Ship Salvage",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 127: Void Cartography — Common, 6 pieces
data modify storage evercraft:lore sets.s127 set value {name:"Void Cartography",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 128: Ender Dragon Lore — Rare, 5 pieces
data modify storage evercraft:lore sets.s128 set value {name:"Ender Dragon Lore",dim:2,cat:"universal",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 129: End Poetry — Common, 6 pieces
data modify storage evercraft:lore sets.s129 set value {name:"End Poetry",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 130: Gateway Studies — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s130 set value {name:"Gateway Studies",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 131: End Archaeology — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s131 set value {name:"End Archaeology",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 132: Void Survival Kit — Common, 6 pieces
data modify storage evercraft:lore sets.s132 set value {name:"Void Survival Kit",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 133: Purpur Architecture — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s133 set value {name:"Purpur Architecture",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 134: End Lighting — Common, 6 pieces
data modify storage evercraft:lore sets.s134 set value {name:"End Lighting",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 135: Ender Chest Secrets — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s135 set value {name:"Ender Chest Secrets",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 136: End Fauna — Common, 6 pieces
data modify storage evercraft:lore sets.s136 set value {name:"End Fauna",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 137: Void Alchemy — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s137 set value {name:"Void Alchemy",dim:2,cat:"universal",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 138: End Construction — Common, 6 pieces
data modify storage evercraft:lore sets.s138 set value {name:"End Construction",dim:2,cat:"universal",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# === LORE NARRATIVE SETS ===

# Set 139: The First Dreamers — Mythical, 8 pieces
data modify storage evercraft:lore sets.s139 set value {name:"The First Dreamers",dim:3,cat:"lore",ctx:0,rarity:6,pieces:8,dr:100,xp:50,crate:6}

# Set 140: Whispers of the Weave — Exquisite, 7 pieces
data modify storage evercraft:lore sets.s140 set value {name:"Whispers of the Weave",dim:3,cat:"lore",ctx:0,rarity:5,pieces:7,dr:80,xp:25,crate:5}

# Set 141: The Patrons' Covenant — Exquisite, 7 pieces
data modify storage evercraft:lore sets.s141 set value {name:"The Patrons' Covenant",dim:3,cat:"lore",ctx:0,rarity:5,pieces:7,dr:80,xp:25,crate:5}

# Set 142: Furia Genesis — Ornate, 6 pieces
data modify storage evercraft:lore sets.s142 set value {name:"Furia Genesis",dim:3,cat:"lore",ctx:0,rarity:4,pieces:6,dr:65,xp:15,crate:4}

# Set 143: The Sundered Portal — Mythical, 8 pieces
data modify storage evercraft:lore sets.s143 set value {name:"The Sundered Portal",dim:3,cat:"lore",ctx:0,rarity:6,pieces:8,dr:100,xp:50,crate:6}

# Set 144: Echoes in the Deep — Rare, 5 pieces
data modify storage evercraft:lore sets.s144 set value {name:"Echoes in the Deep",dim:3,cat:"lore",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 145: The Five Records — Exquisite, 7 pieces
data modify storage evercraft:lore sets.s145 set value {name:"The Five Records",dim:3,cat:"lore",ctx:0,rarity:5,pieces:7,dr:80,xp:25,crate:5}

# Set 146: Rift-Torn Lands — Ornate, 6 pieces
data modify storage evercraft:lore sets.s146 set value {name:"Rift-Torn Lands",dim:3,cat:"lore",ctx:0,rarity:4,pieces:6,dr:65,xp:15,crate:4}

# Set 147: The Architect's Journal — Rare, 5 pieces
data modify storage evercraft:lore sets.s147 set value {name:"The Architect's Journal",dim:3,cat:"lore",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 148: Songs of the Crimson — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s148 set value {name:"Songs of the Crimson",dim:3,cat:"lore",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 149: The Alloy Almanac — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s149 set value {name:"The Alloy Almanac",dim:3,cat:"lore",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 150: Beast Bonds — Common, 6 pieces
data modify storage evercraft:lore sets.s150 set value {name:"Beast Bonds",dim:3,cat:"lore",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 151: Tides of Fortune — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s151 set value {name:"Tides of Fortune",dim:3,cat:"lore",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 152: The Tree of Stars — Rare, 5 pieces
data modify storage evercraft:lore sets.s152 set value {name:"The Tree of Stars",dim:3,cat:"lore",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 153: Hearthfire Memories — Common, 6 pieces
data modify storage evercraft:lore sets.s153 set value {name:"Hearthfire Memories",dim:3,cat:"lore",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 154: The Wanderer's Oath — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s154 set value {name:"The Wanderer's Oath",dim:3,cat:"lore",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 155: Forge of the Titans — Ornate, 6 pieces
data modify storage evercraft:lore sets.s155 set value {name:"Forge of the Titans",dim:3,cat:"lore",ctx:0,rarity:4,pieces:6,dr:65,xp:15,crate:4}

# Set 156: Crystal Dreams — Rare, 5 pieces
data modify storage evercraft:lore sets.s156 set value {name:"Crystal Dreams",dim:3,cat:"lore",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 157: The Lucid Threshold — Uncommon, 5 pieces
data modify storage evercraft:lore sets.s157 set value {name:"The Lucid Threshold",dim:3,cat:"lore",ctx:0,rarity:2,pieces:5,dr:35,xp:5,crate:2}

# Set 158: Moon Cycles and Madness — Common, 6 pieces
data modify storage evercraft:lore sets.s158 set value {name:"Moon Cycles and Madness",dim:3,cat:"lore",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 159: The Shattered Codex — Ornate, 6 pieces
data modify storage evercraft:lore sets.s159 set value {name:"The Shattered Codex",dim:3,cat:"lore",ctx:0,rarity:4,pieces:6,dr:65,xp:15,crate:4}

# Set 160: Keeper of the Tomb — Common, 6 pieces
data modify storage evercraft:lore sets.s160 set value {name:"Keeper of the Tomb",dim:3,cat:"lore",ctx:0,rarity:1,pieces:6,dr:25,xp:3,crate:1}

# Set 161: The Harmonization — Rare, 5 pieces
data modify storage evercraft:lore sets.s161 set value {name:"The Harmonization",dim:3,cat:"lore",ctx:0,rarity:3,pieces:5,dr:50,xp:10,crate:3}

# Set 162: Prophecy of Convergence — Mythical, 8 pieces
data modify storage evercraft:lore sets.s162 set value {name:"Prophecy of Convergence",dim:3,cat:"lore",ctx:0,rarity:6,pieces:8,dr:100,xp:50,crate:6}

