# Lore Data: Load pool mappings to storage
# Called from lore/load.mcfunction
# Generated by generate_lore.py — DO NOT EDIT MANUALLY
# Maps dimension+category+context -> list of set indices

# === BIOME POOLS (per biome_id, per dimension) ===
# The End -> sets [112]
data modify storage evercraft:lore pools.end_biome_23 set value [112]
# Nether Wastes -> sets [82, 83]
data modify storage evercraft:lore pools.nether_biome_18 set value [82, 83]
# Crimson Forest -> sets [84, 85]
data modify storage evercraft:lore pools.nether_biome_19 set value [84, 85]
# Warped Forest -> sets [86, 87]
data modify storage evercraft:lore pools.nether_biome_20 set value [86, 87]
# Basalt Deltas -> sets [88, 89]
data modify storage evercraft:lore pools.nether_biome_21 set value [88, 89]
# Soul Sand Valley -> sets [90, 91]
data modify storage evercraft:lore pools.nether_biome_22 set value [90, 91]
# Plains -> sets [1]
data modify storage evercraft:lore pools.ow_biome_0 set value [1]
# Forest -> sets [2]
data modify storage evercraft:lore pools.ow_biome_1 set value [2]
# River -> sets [11]
data modify storage evercraft:lore pools.ow_biome_10 set value [11]
# Swamp -> sets [12]
data modify storage evercraft:lore pools.ow_biome_11 set value [12]
# Mushroom -> sets [13]
data modify storage evercraft:lore pools.ow_biome_12 set value [13]
# Ice -> sets [14]
data modify storage evercraft:lore pools.ow_biome_13 set value [14]
# Badlands -> sets [15]
data modify storage evercraft:lore pools.ow_biome_14 set value [15]
# Lush Caves -> sets [16]
data modify storage evercraft:lore pools.ow_biome_15 set value [16]
# Dripstone Caves -> sets [17]
data modify storage evercraft:lore pools.ow_biome_16 set value [17]
# Deep Dark -> sets [18]
data modify storage evercraft:lore pools.ow_biome_17 set value [18]
# Flower Forest -> sets [3]
data modify storage evercraft:lore pools.ow_biome_2 set value [3]
# Windswept -> sets [19]
data modify storage evercraft:lore pools.ow_biome_24 set value [19]
# Underground -> sets [20]
data modify storage evercraft:lore pools.ow_biome_25 set value [20]
# Dark Forest -> sets [4]
data modify storage evercraft:lore pools.ow_biome_3 set value [4]
# Taiga -> sets [5]
data modify storage evercraft:lore pools.ow_biome_4 set value [5]
# Mountain -> sets [6]
data modify storage evercraft:lore pools.ow_biome_5 set value [6]
# Jungle -> sets [7]
data modify storage evercraft:lore pools.ow_biome_6 set value [7]
# Desert -> sets [8]
data modify storage evercraft:lore pools.ow_biome_7 set value [8]
# Savanna -> sets [9]
data modify storage evercraft:lore pools.ow_biome_8 set value [9]
# Ocean -> sets [10]
data modify storage evercraft:lore pools.ow_biome_9 set value [10]

# === STRUCTURE POOLS (per structure_id, per dimension) ===
# End City -> sets [113, 114]
data modify storage evercraft:lore pools.end_struct_18 set value [113, 114]
# Bastion Remnant -> sets [92, 93]
data modify storage evercraft:lore pools.nether_struct_2 set value [92, 93]
# Fortress -> sets [94, 95]
data modify storage evercraft:lore pools.nether_struct_4 set value [94, 95]
# Ancient City -> sets [21, 22]
data modify storage evercraft:lore pools.ow_struct_1 set value [21, 22]
# Ocean Ruin -> sets [35, 36]
data modify storage evercraft:lore pools.ow_struct_10 set value [35, 36]
# Pillager Outpost -> sets [37, 38]
data modify storage evercraft:lore pools.ow_struct_11 set value [37, 38]
# Ruined Portal -> sets [39, 40]
data modify storage evercraft:lore pools.ow_struct_12 set value [39, 40]
# Shipwreck -> sets [41, 42]
data modify storage evercraft:lore pools.ow_struct_13 set value [41, 42]
# Stronghold -> sets [43, 44]
data modify storage evercraft:lore pools.ow_struct_14 set value [43, 44]
# Trail Ruins -> sets [45, 46]
data modify storage evercraft:lore pools.ow_struct_15 set value [45, 46]
# Trial Chambers -> sets [47, 48]
data modify storage evercraft:lore pools.ow_struct_16 set value [47, 48]
# Village -> sets [49, 50]
data modify storage evercraft:lore pools.ow_struct_17 set value [49, 50]
# Desert Pyramid -> sets [23, 24]
data modify storage evercraft:lore pools.ow_struct_3 set value [23, 24]
# Igloo -> sets [25, 26]
data modify storage evercraft:lore pools.ow_struct_5 set value [25, 26]
# Jungle Pyramid -> sets [27, 28]
data modify storage evercraft:lore pools.ow_struct_6 set value [27, 28]
# Mansion -> sets [29, 30]
data modify storage evercraft:lore pools.ow_struct_7 set value [29, 30]
# Mineshaft -> sets [31, 32]
data modify storage evercraft:lore pools.ow_struct_8 set value [31, 32]
# Monument -> sets [33, 34]
data modify storage evercraft:lore pools.ow_struct_9 set value [33, 34]

# === UNIVERSAL POOLS (per dimension) ===
data modify storage evercraft:lore pools.end_universal set value [115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138]
data modify storage evercraft:lore pools.nether_universal set value [96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111]
data modify storage evercraft:lore pools.ow_universal set value [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81]

# === LORE NARRATIVE POOL ===
data modify storage evercraft:lore pools.lore_all set value [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162]

# === GUI FLAT POOLS (for Codex set list browsing) ===
# Key format: gui.{dim}_{subcat} (1=biome, 2=struct, 3=universal, 4=lore)
data modify storage evercraft:lore gui.0_1 set value [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
data modify storage evercraft:lore gui.0_2 set value [21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
data modify storage evercraft:lore gui.0_3 set value [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81]
data modify storage evercraft:lore gui.1_1 set value [82, 83, 84, 85, 86, 87, 88, 89, 90, 91]
data modify storage evercraft:lore gui.1_2 set value [92, 93, 94, 95]
data modify storage evercraft:lore gui.1_3 set value [96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111]
data modify storage evercraft:lore gui.2_1 set value [112]
data modify storage evercraft:lore gui.2_2 set value [113, 114]
data modify storage evercraft:lore gui.2_3 set value [115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138]
data modify storage evercraft:lore gui.3_4 set value [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162]

# === DIMENSION CATEGORY AVAILABILITY ===
data modify storage evercraft:lore avail.ow_biome set value 1
data modify storage evercraft:lore avail.ow_struct set value 1
data modify storage evercraft:lore avail.ow_universal set value 1
data modify storage evercraft:lore avail.nether_biome set value 1
data modify storage evercraft:lore avail.nether_struct set value 1
data modify storage evercraft:lore avail.nether_universal set value 1
data modify storage evercraft:lore avail.end_biome set value 1
data modify storage evercraft:lore avail.end_struct set value 1
data modify storage evercraft:lore avail.end_universal set value 1
data modify storage evercraft:lore avail.lore set value 1
